import type { MintProject } from "./types"

export const mockMints: MintProject[] = [
  {
    id: "1",
    name: "Cyber Punks Genesis",
    image: "/cyberpunk-neon-avatar.jpg",
    status: "live",
    price: "0 USDC",
    supply: 1000,
    minted: 342,
    network: "Arc Testnet",
    startTime: new Date(Date.now() - 86400000),
    endTime: new Date(Date.now() + 172800000),
    description:
      "First generation of Cyber Punks on Arc Testnet. Experimental NFT collection featuring neon-styled avatars.",
    walletLimit: 5,
  },
  {
    id: "2",
    name: "Digital Flora",
    image: "/digital-plant-art-neon.jpg",
    status: "live",
    price: "0 USDC",
    supply: 500,
    minted: 89,
    network: "Arc Testnet",
    startTime: new Date(Date.now() - 43200000),
    endTime: new Date(Date.now() + 259200000),
    description: "Generative botanical art collection. Each piece is uniquely generated on-chain.",
    walletLimit: 3,
  },
  {
    id: "3",
    name: "Arc Builders Pass",
    image: "/futuristic-access-card.png",
    status: "live",
    price: "0 USDC",
    supply: 2000,
    minted: 1847,
    network: "Arc Testnet",
    startTime: new Date(Date.now() - 259200000),
    endTime: new Date(Date.now() + 86400000),
    description: "Official builders pass for Arc ecosystem. Grants access to exclusive builder tools and communities.",
    walletLimit: 1,
  },
  {
    id: "4",
    name: "Quantum Shapes",
    image: "/abstract-geometric-shapes-glowing.jpg",
    status: "upcoming",
    price: "0 USDC",
    supply: 777,
    minted: 0,
    network: "Arc Testnet",
    startTime: new Date(Date.now() + 86400000),
    endTime: new Date(Date.now() + 432000000),
    description: "Abstract geometric NFTs exploring quantum visual effects. Minting begins in 24 hours.",
    walletLimit: 10,
  },
  {
    id: "5",
    name: "Neon Nights",
    image: "/neon-city-night-scene.jpg",
    status: "upcoming",
    price: "0 USDC",
    supply: 1500,
    minted: 0,
    network: "Arc Testnet",
    startTime: new Date(Date.now() + 172800000),
    endTime: new Date(Date.now() + 604800000),
    description: "Atmospheric cityscape collection capturing cyberpunk aesthetics. Coming in 2 days.",
    walletLimit: 5,
  },
  {
    id: "6",
    name: "Genesis Labs",
    image: "/laboratory-science-fiction.jpg",
    status: "ended",
    price: "0 USDC",
    supply: 100,
    minted: 100,
    network: "Arc Testnet",
    startTime: new Date(Date.now() - 604800000),
    endTime: new Date(Date.now() - 86400000),
    description: "Limited genesis collection from the first Arc Testnet experiments. Fully minted.",
    walletLimit: 2,
  },
  {
    id: "7",
    name: "Pixel Legends",
    image: "/pixel-art-character-retro.jpg",
    status: "ended",
    price: "0 USDC",
    supply: 800,
    minted: 800,
    network: "Arc Testnet",
    startTime: new Date(Date.now() - 432000000),
    endTime: new Date(Date.now() - 172800000),
    description: "Retro-style pixel art NFT collection. Successfully completed on testnet.",
    walletLimit: 3,
  },
]
